apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap1
  namespace: default  # specify your namespace here if needed
data:
  # Properties-style configuration
  application.properties: |
    APP_NAME=MyApp
    APP_VERSION=1.0
    DATABASE_URL=jdbc:mysql://localhost:3306/mydb
    DATABASE_USERNAME=root
    DATABASE_PASSWORD=password

  # Plain text key-value pairs
  log_level: "DEBUG"
  app_environment: "production"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap2
  namespace: default  # specify your namespace here if needed
data:
  # Properties-style configuration
  application.properties: |
    APP_NAME=MyApp
    APP_VERSION=1.0
    DATABASE_URL=jdbc:mysql://localhost:3306/mydb
    DATABASE_USERNAME=root
    DATABASE_PASSWORD=password

  # Plain text key-value pairs
  log_level: "DEBUG"
  app_environment: "production"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap3jagiQJDBKASBFO
  namespace: default  # specify your namespace here if needed
data:
  # Properties-style configuration
  application.properties: |
    APP_NAME=MyApp
    APP_VERSION=1.0
    DATABASE_URL=jdbc:mysql://localhost:3306/mydb
    DATABASE_USERNAME=root
    DATABASE_PASSWORD=password

  # Plain text key-value pairs
  log_level: "DEBUG"
  app_environment: "production"
